### ISSUE TITLE
Fails to check when account has 2FA enabled

### ISSUE THREAD

**Issue by FerrahWolfeh** [servusdei2018/protoncheck#1]
If you have an account with 2-Factor auth enabled, protoncheck fails with an `Access token does not have sufficient scope` error.

also, when you look at protonmail session logs, it says that the authentication was successful, but its waiting for the 2FA authentication

**Comment by servusdei2018** [comment]
Hmm, for 2FA accounts I don't think it'd be possible to enable the module as there'd be no way to input a 2FA code into the status bar, and protoncheck runs frequently enough (~30s) that it would become an annoyance.
